version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 918426310334.dkr.ecr.us-east-1.amazonaws.com
      - echo "*************************"
      - whoami
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - ls
      - mv target/HelloWorld-2.6.5.war target/white-hart.war
      - docker build -t white-hart:latest .
      - docker tag white-hart:latest 596720955985.dkr.ecr.us-east-1.amazonaws.com/test:latest
      - docker push 596720955985.dkr.ecr.us-east-1.amazonaws.com/test:latest
      - pwd
      # - aws ecs list-services --cluster white-hart | jq -r .serviceArns[]  | grep white-hart | awk -F/ {'print $3'}  > consumer-services.txt
      # - consumer=`cat consumer-services.txt`
      # - for i in ${consumer}; do aws ecs list-tasks --cluster white-hart --service-name $i | jq -r .taskArns[] | awk -F/ {'print $3'} >> task-ids.txt; done
      # - tasks=`cat task-ids.txt`
      # - for j in ${tasks}; do aws ecs stop-task --task $j --cluster white-hart; done
      # New
#       - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "new" --region us-east-1)
#       - NEW_TASK_DEFINITION=$(echo ${TASK_DEFINITION} | jq --arg IMAGE "707909915006.dkr.ecr.us-east-1.amazonaws.com/white-hart:latest" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities)')
#       - NEW_TASK_INFO=$(aws ecs register-task-definition --region us-east-1 --cli-input-json "${NEW_TASK_DEFINITION}")
#       - NEW_REVISION=$(echo ${NEW_TASK_INFO} | jq '.taskDefinition.revision')
#       - echo "NEW_REVISION is $NEW_REVISION"
#       - echo "***********************************"
#       - echo "Running update service for $NAME micro service with version $NEW_REVISION"
#       - aws ecs update-service --cluster white-hart --service white-hart --region us-east-1 --task-definition new:${NEW_REVISION} --desired-count 1 --force-new-deployment --deployment-configuration "maximumPercent=200,minimumHealthyPercent=100"
  post_build:
    commands:
      - echo Build completed on `date`
      - IMAGE=596720955985.dkr.ecr.us-east-1.amazonaws.com/test:latest
      - sed -r "s/^(\s*image\s*:\s*).*/\1${IMAGE}/" -i "deployment.yml"
      - echo "updated image"
      - export AWS_ACCESS_KEY_ID="AKIAYV32XGJI4YJRIYKP"
      - export AWS_SECRET_ACCESS_KEY="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"
      - aws s3 ls
      - aws eks update-kubeconfig --name eksdemo1
      - kubectl apply -f deployment.yml
artifacts:
  files:
    - target/*.war
